---
- hosts: all
  tasks:
    - name: creates users files
      file:
        path: /tmp/ansible-{{ item }}
        state: touch
      loop:
        - sarfaraz
        - www-data
        - test

#### Here we are creating file using loop 