apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    pv-name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nginx
